name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into DigitalOcean Droplet
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DROPLET_IP }} # Replace with your Droplet's IP address
          username: ${{ secrets.SSH_USERNAME }} # Replace with your SSH username
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Add your private SSH key as a secret
          port: ${{ secrets.SSH_PORT }} # Replace with your SSH port (default is 22)
          script: |
            cd /apps/Prisma-SSO-TEST/
            ./deploy.sh main
